"""Build the reproducibility appendix (Excel + Markdown) from nhgis_search.py's own
constants, the Keyword Spec workbook, the catalog cache, and nhgis_extract_spec.json.
Run from the Research - Ma'el folder after nhgis_search.py.
"""
import json
import pandas as pd
import nhgis_search as ns

spec_json = json.load(open(ns.EXTRACT_SPEC_PATH))
ks = pd.read_excel(ns.KEYWORD_SPEC_PATH, sheet_name="Keyword Spec")
tables = json.load(open(ns.CACHE_DATA_TABLES))
desc = {(t["datasetName"], t["name"]): t["description"] for t in tables}

# ---- Table A: extract definition (one row per table code) --------------------
rows_a = []
for ds, body in spec_json["datasets"].items():
    for code in body["dataTables"]:
        rows_a.append({"Extract": "Primary (ACS 2018-2022)", "Dataset": ds, "Table code": code,
                       "NHGIS table title": desc.get((ds, code), ""), "Geographic level": ", ".join(body["geogLevels"]),
                       "Extent": ", ".join(spec_json["geographicExtents"]) + " (California)"})
hist = spec_json.get("_historical_extract_separate", {})
for ds, body in hist.get("datasets", {}).items():
    for code in body["dataTables"]:
        rows_a.append({"Extract": "Secondary (1940 tracts)", "Dataset": ds, "Table code": code,
                       "NHGIS table title": desc.get((ds, code), ""), "Geographic level": ", ".join(body["geogLevels"]),
                       "Extent": "all available (no extent selection for this dataset)"})
for shp in spec_json["shapefiles"]:
    rows_a.append({"Extract": "Primary (ACS 2018-2022)", "Dataset": "GIS", "Table code": shp,
                   "NHGIS table title": "2020 census tract boundaries (TIGER/Line basis)", "Geographic level": "tract",
                   "Extent": "060 (California)"})
table_a = pd.DataFrame(rows_a)

# ---- Table B: extract parameters -------------------------------------------
params = [
    ("Data collection", "IPUMS NHGIS (nhgis.org), Version 21.0, doi:10.18128/D050.V21.0"),
    ("Access route", "IPUMS API v2: POST https://api.ipums.org/extracts?collection=nhgis&version=2 (or the NHGIS Data Finder with the same selections)"),
    ("Request body", "nhgis_extract_spec.json (generated by nhgis_search.py)"),
    ("Datasets", ", ".join(spec_json["datasets"].keys())),
    ("Geographic level", ns.DEFAULT_GEOG + " (2020 census tracts)"),
    ("Geographic extent", "060 = California (NHGIS state code = FIPS x 10)"),
    ("Shapefile", ", ".join(spec_json["shapefiles"])),
    ("dataFormat", spec_json["dataFormat"] + " (CSV with descriptive second header row)"),
    ("breakdownAndDataTypeLayout", spec_json["breakdownAndDataTypeLayout"] + " (estimates and margins of error in one file)"),
    ("Secondary extract", "1940_tPH_Major tables " + ", ".join(hist.get("datasets", {}).get("1940_tPH_Major", {}).get("dataTables", [])) + " at tract level, submitted separately"),
    ("Join key", "GISJOIN -> GEOID (drop leading 'G' and the two zero pads: G0600370207400 -> 06037207400)"),
    ("Catalog snapshot used for table selection", "IPUMS API metadata endpoints datasets, data_tables, time_series_tables; cached 2026-04-16 (nhgis_*_cache.json)"),
    ("Search script", "nhgis_search.py v2 (Sept 2026); python nhgis_search.py --refresh to re-pull the catalog"),
]
table_b = pd.DataFrame(params, columns=["Parameter", "Value"])

# ---- Table C: keyword provenance (determinant -> search terms -> tables) -----
rows_c = []
for _, r in ks.iterrows():
    if pd.isna(r["#"]):
        continue
    num = int(r["#"])
    cur = ns.CURATED.get(num, {})
    codes = cur.get("codes", []) + [h.split(":")[1] + " (" + h.split(":")[0] + ")" for h in cur.get("hist", [])]
    census = "; ".join(f"{t} ({w})" for t, w in ns.CENSUS_TERMS.get(num, []) if w > 0)
    if num in ns.EXTERNAL_SOURCE:
        outcome = "Not from NHGIS: " + ns.EXTERNAL_SOURCE[num]
    elif cur.get("shapefile"):
        outcome = "From tract geometry (shapefile)"
    elif codes:
        outcome = "NHGIS tables selected"
    else:
        outcome = "No NHGIS table"
    rows_c.append({
        "#": num, "Determinant": r["Determinant"], "Category": r["Category"],
        "Primary keywords (weight 2)": r["Primary Keywords (exact terms)"],
        "Secondary keywords (weight 1)": r["Secondary Keywords (broader/related terms)"],
        "Exclusion terms": r["Exclusion Terms (avoid false positives)"],
        "Census-vocabulary terms added in v2 (weight)": census,
        "Outcome": outcome,
        "Tables selected": ", ".join(codes),
        "Construction note": cur.get("note", ""),
    })
table_c = pd.DataFrame(rows_c)

# ---- Table D: matching rules ------------------------------------------------
rules = [
    ("Search space", "All 54,148 NHGIS source tables and 400 time series tables in the catalog snapshot; nothing excluded before matching."),
    ("Fields searched", "Table description and universe, lower-cased."),
    ("Match rule", "Each term is matched as a whole phrase on word boundaries (regex \\b...\\b), case-insensitive; hyphen/space/slash between words are interchangeable. Parenthetical qualifiers in spec keywords are stripped."),
    ("Scoring", "Score = sum of weights of distinct terms that hit (primary 2, secondary 1, Census-vocabulary as listed). Tables with score 0 are dropped; exclusion terms remove a table if they hit."),
    ("Partition", "Hits are reported separately for the locked vintage (2018_2022_ACS5a/b), other 2010+ datasets, 1940-1970 tract datasets, and time series tables with tract geography."),
    ("Geography filter", "A table is kept only if its dataset offers tract, block group, or block (from the dataset's geogLevels when fetched, else inferred from the dataset description)."),
    ("Final selection", "Table codes were chosen by the analyst from the ranked hits and fixed in the CURATED map of nhgis_search.py; the script validates each code exists in the locked vintage and resolves its a/b dataset."),
]
table_d = pd.DataFrame(rules, columns=["Rule", "Definition"])

out_x = ns.SCRIPT_DIR / "Appendix_NHGIS_Reproducibility.xlsx"
with pd.ExcelWriter(out_x) as w:
    table_b.to_excel(w, sheet_name="A. Extract parameters", index=False)
    table_a.to_excel(w, sheet_name="B. Tables requested", index=False)
    table_c.to_excel(w, sheet_name="C. Keyword provenance", index=False)
    table_d.to_excel(w, sheet_name="D. Matching rules", index=False)

md = ["# Appendix: NHGIS data extraction (reproducibility)\n",
      "## Table A. Extract parameters\n", table_b.to_markdown(index=False),
      "\n\n## Table B. Tables requested\n", table_a.to_markdown(index=False),
      "\n\n## Table C. Keyword provenance (determinant -> search terms -> tables)\n", table_c.fillna("").to_markdown(index=False),
      "\n\n## Table D. Matching rules\n", table_d.to_markdown(index=False), "\n"]
(ns.SCRIPT_DIR / "Appendix_NHGIS_Reproducibility.md").write_text("\n".join(md))
print(f"wrote {out_x.name} and .md  |  A={len(table_a)} tables, C={len(table_c)} determinants")
